image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    # Costruisci l'immagine Docker e taggala con l'identificativo del commit
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
  tags:
    - docker

test:
  stage: test
  script:
    # Se hai test automatizzati, eseguili qui.
    # Per esempio, puoi eseguire "go test ./..." per i test Go
    - echo "Esegui eventuali test automatizzati qui..."
    # Esempio: go test ./...
  tags:
    - docker

deploy:
  stage: deploy
  script:
    # Esegui il login al Container Registry di GitLab
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # Pusha l’immagine costruita
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - branch_venerdi
  tags:
    - docker
